### ISSUE TITLE
lacking installation instruction  - the sandcrawler companion

### ISSUE THREAD

**Issue by danieleguido** [Yomguithereal/sandcrawler-logger#3]
Back to scrape, I found that this awesome plugin does not appear on npm ... and without it, my sandcrawler scraper is quite blind.
Tried to install with:

     npm install Yomguithereal/sandcrawler-logger

Is that correct?

**Comment by Yomguithereal** [comment]
Nope

```
npm install git+https://github.com/Yomguithereal/sandcrawler-logger.git
```
